# Generated by Django 3.2.9 on 2021-12-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cod_ecad', models.IntegerField(null=True, verbose_name='Cód.ECAD')),
                ('type_doc', models.CharField(choices=[('J', 'JURIDÍCA'), ('F', 'FÍSICA')], default='F', max_length=1, verbose_name='Tipo Pessoa')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=16, verbose_name='CNPJ')),
                ('ifpi', models.CharField(blank=True, max_length=3, verbose_name='IFPI')),
                ('radical_ifpi', models.CharField(blank=True, max_length=2, verbose_name='RADICAL IFPI')),
                ('is_editora', models.BooleanField(default=False, verbose_name='É EDITORA')),
                ('is_produtor_fono', models.BooleanField(default=False, verbose_name='É PRODUTOR FONOGRAFICO')),
                ('is_interprete', models.BooleanField(default=False, verbose_name='É INTERPRETE')),
                ('is_autor', models.BooleanField(default=False, verbose_name='É AUTOR')),
                ('is_musico', models.BooleanField(default=False, verbose_name='É MUSICO')),
                ('is_deleted', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, verbose_name='OBSERVAÇÃO')),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
            },
        ),
    ]
