# Generated by Django 3.2.9 on 2021-12-08 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holders', '0002_auto_20211208_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pseudonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=100, verbose_name='Pseudônimo')),
                ('is_main', models.BooleanField(verbose_name='É o Principal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holder',
            name='pseudonyms',
            field=models.ManyToManyField(blank=True, null=True, to='holders.Pseudonym'),
        ),
    ]
