# Generated by Django 3.2.9 on 2021-12-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0003_auto_20211208_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holder',
            old_name='is_autor',
            new_name='is_author',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='is_interprete',
            new_name='is_interpreter',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='is_musico',
            new_name='is_musician',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='is_editora',
            new_name='is_publisher',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='is_produtor_fono',
            new_name='is_record_producer',
        ),
        migrations.RenameField(
            model_name='holder',
            old_name='observacao',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='holder',
            name='pseudonyms',
            field=models.ManyToManyField(blank=True, to='holders.Pseudonym'),
        ),
    ]
