# Generated by Django 3.2.9 on 2021-12-08 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holders', '0004_auto_20211208_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='pseudonyms',
            field=models.ManyToManyField(blank=True, to='holders.Pseudonym', verbose_name='Pseudonimo'),
        ),
        migrations.AlterField(
            model_name='pseudonym',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='É o Principal'),
        ),
    ]
