# Generated by Django 3.2.9 on 2021-12-10 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holders', '0005_auto_20211208_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='pseudonyms',
        ),
        migrations.AddField(
            model_name='holder',
            name='pseudonyms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='holders.pseudonym', verbose_name='Pseudonimo'),
        ),
        migrations.AlterField(
            model_name='pseudonym',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
