# Generated by Django 3.2.9 on 2021-12-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holders', '0008_auto_20211222_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pseudonym',
            options={'verbose_name': 'Pseudônimo', 'verbose_name_plural': 'Pseudônimos'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name': 'Sociedade', 'verbose_name_plural': 'Sociedades'},
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('E', 'Email'), ('P', 'Telefone')], max_length=1, verbose_name='Tipo')),
                ('value', models.CharField(max_length=50, verbose_name='Valor')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holders.holder', verbose_name='Titular')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
    ]
